class Error < Exception {}
class SubError < Error {}

try {
    try {
        throw SubError("error message");
    } catch Error {
        print("Caught Error"); # expect: Caught Error
    }
} catch SubError {
    print("Caught SubError");
}
