class Error < Exception {}

fun get_exception() {
    return Error;
}

try {
    throw Error("error message");
} catch get_exception() {
    print("Catch"); # expect: Catch
}
