class Error1 < Exception {}
class Error2 < Exception {}
class Error3 < Exception {}

fun get_exception() {
    throw Error1("error message");
}


try{
    try {
        throw Error2("error message");
    } catch get_exception()  {
        print("Catch");
    } catch Error1 {
        print("Catch Error1");
    }
}  catch Error1 {
    print("Catch Error1");  # expect: Catch Error1
}
