class Error1 < Exception {}
class Error2 < Exception {}
class Error3 < Exception {}
class Error4 < Exception {}

fun second() {
    try {
        throw Error1("error message");
    } catch Error4 {
        print("Catch third");
    }
}

fun first() {
    try {
        second();
    } catch Error3 as e {
        print(e);
    }
}

try {
    first(); # expect runtime error: Error1: error message
} catch Error2 as e {
    print(e);
}